// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsXw6Ug_uoom3qZreJGhRRMTk06hB-BoY',
    appId: '1:296143356306:web:fe29e33a14783a69a8c14b',
    messagingSenderId: '296143356306',
    projectId: 'gdg-iom',
    authDomain: 'gdg-iom.firebaseapp.com',
    storageBucket: 'gdg-iom.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFtKJLJeKjx_h9qJ-omBx8SHoy9QWqFjc',
    appId: '1:296143356306:android:7e2fea690bab62e8a8c14b',
    messagingSenderId: '296143356306',
    projectId: 'gdg-iom',
    storageBucket: 'gdg-iom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYElcsGSVBEvMDfPLDaHYhAOJJq6bJxQs',
    appId: '1:296143356306:ios:d2fa4273b4600c7fa8c14b',
    messagingSenderId: '296143356306',
    projectId: 'gdg-iom',
    storageBucket: 'gdg-iom.appspot.com',
    iosBundleId: 'com.example.gdgflutterDemo',
  );

}